### PR TITLE
`use v6` must be on the first line

### PR DESCRIPTION
**Pull request by AlexDaniel**
Also renames .pm → .pm6

### CODE REVIEW

**Comment by donaldh** [comment]
vote +1 for this

**Comment by AlexDaniel** [comment]
@avuserow any reason why this can't be merged? Technically it's just one line being moved.

**Comment by AlexDaniel** [comment]
Thank you!

**Comment by avuserow** [comment]
@AlexDaniel other than the unfortunate degradation of Perl 5 error messages when incorrectly used, the only problem is that the GitHub notifications sometimes get lost for me. Please feel free to ping me in IRC, on the ticket directly, via email, twitter, etc if something needs attention.

Thanks for your help keeping the ecosystem in good shape. It makes a huge difference that I can typically count on modules not being bitrotted when I do get the occasional time to program on side projects.

**Pull request merged**
